# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('reminders_messages', '0005_auto_20151119_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='ident',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(40,), **{}), max_length=40, unique=True),
        ),
    ]
