# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-19 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('reminders_calls', '0004_auto_20151117_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'get_latest_by': 'created', 'ordering': ('created',)},
        ),
        migrations.AddField(
            model_name='call',
            name='state_updated',
            field=models.DateTimeField(default=datetime.datetime.utcnow),
        ),
        migrations.AlterField(
            model_name='call',
            name='ident',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(40,), **{}), max_length=40, unique=True),
        ),
    ]
