INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'djcelery',
    'email_from_template',
    'template_tests',

    'takeyourmeds.account',
    'takeyourmeds.account.forgot_password',
    'takeyourmeds.dashboard',
    'takeyourmeds.groups',
    'takeyourmeds.groups.groups_admin',
    'takeyourmeds.groups.groups_billing',
    'takeyourmeds.profile',
    'takeyourmeds.recordings',
    'takeyourmeds.registration',
    'takeyourmeds.reminders',
    'takeyourmeds.reminders.reminders_create',
    'takeyourmeds.reminders.reminders_calls',
    'takeyourmeds.reminders.reminders_calls.reminders_calls_audio',
    'takeyourmeds.reminders.reminders_messages',
    'takeyourmeds.static',
    'takeyourmeds.utils',
)
