#!/bin/sh

set -eu

cd "$(dirname "${0}")"

DEBIAN_FRONTEND=noninteractive apt-get install --yes --no-install-recommends ansible

exec ansible-playbook \
	takeyourmeds-web.yml \
	--diff \
	--verbose \
	--inventory=hosts \
	--connection=local \
	--limit="$(hostname --fqdn)" \
	"${@}"
