#!/bin/sh

set -eu

TEMP="$(mktemp -d)"
SOURCE="$(dpkg-parsechangelog --show-field Source)"

case "${TRAVIS_BRANCH:-}" in
	master)
		ROLE="stage"
		HOSTNAME="stage.takeyourmeds.co.uk"
		;;
	live)
		ROLE="live"
		HOSTNAME="live.takeyourmeds.co.uk"
		;;
	*)
		echo "I: Not deploying for TRAVIS_BRANCH=${TRAVIS_BRANCH:-(empty)}"
		exit 0
esac

pip install ansible==1.9.4
install -v -D -m644 ../${SOURCE}_*.deb config/roles/${SOURCE}/files/${SOURCE}.deb

echo "${ANSIBLE_VAULT_PASSWORD}" > ${TEMP}/password
echo "${HOSTNAME} ansible_ssh_user=root ansible_ssh_private_key_file=${TEMP}/id_rsa role=${ROLE}" > ${TEMP}/hosts

cp config/id_rsa ${TEMP}
ansible-vault decrypt --vault-password-file=${TEMP}/password ${TEMP}/id_rsa
chmod 600 "${TEMP}/id_rsa"

exec env ANSIBLE_HOST_KEY_CHECKING=0 ansible-playbook \
	config/playbook.yml \
	--verbose \
	--inventory=${TEMP}/hosts \
	--vault-password-file=${TEMP}/password \
	"${@}"
