# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='audio_file',
            field=models.FileField(upload_to=b'recordings'),
        ),
    ]
