# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-17 18:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0002_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='slug',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(12,), **{}), max_length=12, null=True),
        ),
    ]
