# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-17 18:21
from __future__ import unicode_literals

from django.db import migrations
from django.utils.crypto import get_random_string

def generate_slug(apps, schema_editor):
    Reminder = apps.get_model('reminders', 'Reminder')
    for x in Reminder.objects.all():
        x.slug = get_random_string(12)
        x.save()

class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0003_reminder_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slug, reverse_code=migrations.RunPython.noop),
    ]
