# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-23 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_auto_20151123_1802'),
        ('reminders', '0005_auto_20151117_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recordings.Recording'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='slug',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(12,), **{}), max_length=12, unique=True),
        ),
    ]
