# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-28 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0006_auto_20151123_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='slug',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(12,), **{}), max_length=12, unique=True),
        ),
    ]
