# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-27 19:38
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(8, b'ACEFHKJMLNPRUTWVYX'), **{}), max_length=8, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='groups.Group')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
    ]
