# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-28 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('recordings_create', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createrequest',
            name='ident',
            field=models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(40,), **{}), max_length=40, unique=True),
        ),
    ]
