# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2015-11-14 17:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reminders', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(b'in_progress', 0), (b'success', 10), (b'error', 20)])),
                ('traceback', models.TextField()),
                ('twilio_sid', models.CharField(max_length=34)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='reminders.Reminder')),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
            },
        ),
    ]
